# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tictactien-gem}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tien H. Nguyen"]
  s.date = %q{2011-06-20}
  s.description = %q{Tic-Tac-Toe game in Ruby...}
  s.email = %q{nht007@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ai.rb",
    "lib/board.rb",
    "lib/console_game.rb",
    "lib/cpu_player.rb",
    "lib/game.rb",
    "lib/game_state.rb",
    "lib/human_player.rb",
    "lib/minimax.rb",
    "lib/perfect_ai.rb",
    "lib/player.rb",
    "lib/player_factory.rb",
    "lib/rails_game.rb",
    "lib/random_ai.rb",
    "lib/tictactien-gem.rb",
    "spec/ai_spec.rb",
    "spec/board_spec.rb",
    "spec/console_game_spec.rb",
    "spec/cpu_player_spec.rb",
    "spec/game_spec.rb",
    "spec/game_state_spec.rb",
    "spec/human_player_spec.rb",
    "spec/minimax_spec.rb",
    "spec/perfect_ai_spec.rb",
    "spec/player_factory_spec.rb",
    "spec/player_spec.rb",
    "spec/rails_game_spec.rb",
    "spec/random_ai_spec.rb",
    "spec/spec_helper.rb",
    "spec/spec_helper_jeweler.rb",
    "spec/tictactien-gem_spec.rb",
    "tictactien-gem.gemspec"
  ]
  s.homepage = %q{http://github.com/nht007/tictactien-gem}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Tic-Tac-Toe game in Ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

