# Dir["../lib/*.rb"].each {|file| require file }
#require '../lib/tictactien-gem'
#require '../lib/board'
#require '../lib/game'
#require '../lib/console_game'
#require '../lib/ai'
#require '../lib/player'
#require '../lib/human_player'
#require '../lib/cpu_player'
#require '../lib/minimax'
#require '../lib/perfect_ai'
#require '../lib/random_ai'
#require '../lib/player_factory'
#require '../lib/game_state'

require 'tictactien-gem'
require 'board'
require 'game'
require 'console_game'
require 'ai'
require 'player'
require 'human_player'
require 'cpu_player'
require 'minimax'
require 'perfect_ai'
require 'random_ai'
require 'player_factory'
require 'game_state'
